### ISSUE TITLE
NoneType can't be used in 'await' expression - May be harmless

### ISSUE THREAD

**Issue by jakirkham** [jupyterhub/jupyter-server-proxy#109]
Ran into the following traceback when using dask-labextension with jupyter-server-proxy. This occurred with Tornado 6, but went away with Tornado 5. Am using JupyterLab 0.35.4, dask-labextension 0.3.1, Bokeh 1.0.4, and jupyter-server-proxy 1.0.0.

```python
LabApp - ERROR - Uncaught exception GET /proxy/9100/status (10.110.73.60)
HTTPServerRequest(protocol='http', host='10.31.241.45:9999', method='GET', uri='/proxy/9100/status', version='HTTP/1.1', remote_ip='10.110.73.60')
Traceback (most recent call last):
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 87, in get
    return await self.http_get(*args, **kwargs)
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 247, in http_get
    return await self.proxy(port, proxy_path)
TypeError: object NoneType can't be used in 'await' expression
LabApp - ERROR - Uncaught exception GET /proxy/9100/status (10.110.73.60)
HTTPServerRequest(protocol='http', host='10.31.241.45:9999', method='GET', uri='/proxy/9100/status', version='HTTP/1.1', remote_ip='10.110.73.60')
Traceback (most recent call last):
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 87, in get
    return await self.http_get(*args, **kwargs)
  File "/home/nfs/jkirkham/miniconda/envs/rapidsdev37/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 247, in http_get
    return await self.proxy(port, proxy_path)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by ian-r-rose** [comment]
Thanks for the report @jakirkham, I am also seeing issues with Tornado 6. What notebook version do you have installed? There have been a couple of updates to try to deal with tornado 6 compatibility issues, but was may not be out of the woods yet...

**Comment by quasiben** [comment]
I am seeing similar issues.  I have notebook version 5.7.8 installed

**Comment by jakirkham** [comment]
Sorry for the slow reply, @ian-r-rose. I had ensured the latest notebook with Tornado 6 fixes was installed at the time, but it was a while ago; so, have forgotten the exact version.

Created a new environment and ran into the same issue again recently. It has JupyterLab 0.35.6, dask-labextension 0.3.3, Bokeh 1.1.0, and jupyter-server-proxy 1.1.0. Please let me know if there are any other details you need. 🙂

**Comment by marberi** [comment]
I also get a similar error. In my case, it was previously working fine. The conference internet was slow, so I stopping the server, connected through my cell phone hotspot and then trying to start the server again. Then Jupterlab failed. I use Jupyterlab=0.35.6 and tornado=5.1.1

**Comment by AlJohri** [comment]
I got this error when trying to access the dask dashboard with tornado 6:

```
NotebookApp - ERROR - Uncaught exception GET /proxy/8787/status (10.73.14.200)
HTTPServerRequest(protocol='http', host='10.73.56.224:8888', method='GET', uri='/proxy/8787/status', version='HTTP/1.1', remote_ip='10.73.14.200')
Traceback (most recent call last):
  File "/opt/python3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/opt/python3/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 96, in get
    return await self.http_get(*args, **kwargs)
  File "/opt/python3/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 332, in http_get
    return await self.proxy(port, proxied_path)
  File "/opt/python3/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 213, in proxy
    response = await client.fetch(req, raise_error=False)
ConnectionRefusedError: [Errno 111] Connection refused
```

```
$ pip freeze | egrep 'jupyter|dask|tornado'
dask==2.9.2
dask-labextension==1.1.0
dask-yarn==0.8.0
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.1
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyter-server-proxy==1.2.0
jupyterlab==1.2.5
jupyterlab-server==1.0.6
tornado==6.0.3
```

Not 100% sure if this is the same error other's are running into or not.

**Comment by AlJohri** [comment]
Okay, nevermind- this works! I realized my dask-yarn was starting in remote mode instead of local mode and I think that was the issue.

**Comment by ian-r-rose** [comment]
Glad to hear it @AlJohri

**Comment by maresb** [comment]
Running `code-server` with `tornado==6.0.4`, `jupyter-server-proxy==1.5.0`, `jupyterlab==2.1.1`, and `jupyterlab_server==1.1.1` I periodically encounter the following, which refers to [this line](https://github.com/jupyterhub/jupyter-server-proxy/blob/2abc232745ad5dc4dabac5dfe86438f93d3ec2ec/jupyter_server_proxy/handlers.py#L534) of `handlers.py`:

```
[E 19:33:44.192 LabApp] Uncaught exception GET /vscode/update (172.18.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/vscode/update', version='HTTP/1.1', remote_ip='172.18.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/opt/conda/lib/python3.7/site-packages/jupyter_server_proxy/websocket.py", line 97, in get
        return await self.http_get(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/jupyter_server_proxy/handlers.py", line 534, in http_get
        return await self.proxy(self.port, path)
    TypeError: object NoneType can't be used in 'await' expression
```

**Comment by consideRatio** [comment]
The following tests emit this error and pass.

tests/test_proxies.py::test_server_proxy_minimal_proxy_path_encoding
tests/test_proxies.py::test_server_proxy_minimal_proxy_path_encoding_complement

**Comment by maresb** [comment]
While it doesn't break functionality, having frequent uncaught exceptions is very disconcerting and hinders debugging of other issues.

**Comment by consideRatio** [comment]
@maresb absolutely, solving this would be very appreciated!

**Comment by maresb** [comment]
I considered bundling a fix in https://github.com/jupyterhub/jupyter-server-proxy/pull/209 but it was way too complicated already.

I haven't understood #239 yet but, ignoring testing issues, and if I remember correctly, to solve this issue one simply needs to add checks to all await statements that one isn't awaiting `None`. My solution was to write a helper function, something along the lines of
```python
async def await_if_not_none(awaitable):
    if awaitable is not None:
        return await awaitable
```
and then replace most `await` calls with this. (Disclaimer: I'm writing from memory and that's not tested.)

However, I'm not an `asyncio` expert (yet), and I don't know if there's a more elegant way.

**Comment by consideRatio** [comment]
Thanks for your work thinking about this @maresb, I'm not at all confident about things and feel I've done as much as I can by #240 now. It documents the current behavior by asserting it in tests, and it includes when an invalid token is sent and NoneType error follows in the jupyter notebook server.

**Comment by manics** [comment]
`if awaitable is not None: return await awaitable` could work if it's really true that the awaitable function could return None. However this doesn't fit in with the conventional asyncio style, so I'm worried it might be hiding a genuine bug.

Before wrapping the error could we try and find out the underlying cause?
