### ISSUE TITLE
Bug-fix release

### ISSUE THREAD

**Issue by xhochy** [jupyterhub/jupyter-server-proxy#122]
Hello `jupyter-server-proxy` maintainers. I'm trying to setup https://github.com/betatim/vscode-binder in a more clean fashion and one of the first issues I ran into was that it requires current master of `jupyter-server-proxy` to properly function. Thus depending on how much work it is for you, it would be really kind whether you could make a bugfix release.

**Comment by ryanlovett** [comment]
Fixed by f12a090, thanks!

**Comment by xhochy** [comment]
@ryanlovett Huge thanks for this! 🚀
