### ISSUE TITLE
Enable extension as part of install?

### ISSUE THREAD

**Issue by jakirkham** [jupyterhub/jupyter-server-proxy#127]
When reading [the installation docs]( https://jupyter-server-proxy.readthedocs.io/en/latest/install.html ), it seems we should just `pip install`. Though I recall with `nbserverproxy` previously we needed to enable the server extension as well by running `jupyter-serverextension enable nbserverproxy --py --sys-prefix`. Is that still needed with `jupyter-server-proxy` or not?

cc @xhochy

**Comment by ryanlovett** [comment]
Running `pip install` is sufficient as it puts the requisite data files into the right locations. You [can confirm](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#Did-it-work?-Check-by-listing-Jupyter-Extensions.) by running `jupyter nbextension list` and `jupyter serverextension list`. If you're interested see [setup.py](https://github.com/jupyterhub/jupyter-server-proxy/blob/master/setup.py) and the jupyter docs on [common directories and file locations](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html).

**Comment by jakirkham** [comment]
Thanks for confirming Ryan! After looking at the conda-forge packages, I can see these files are where we would expect them to be 🙂
