### ISSUE TITLE
New User having trouble -- tests fail

### ISSUE THREAD

**Issue by quasiben** [jupyterhub/jupyter-server-proxy#131]
I am having trouble getting tests to pass with master branch

### setup

```
conda create -n test-proxy jupyter python=3.7 tornado=5 pytest
conda activate test-proxy
pip install -e . # master of jupyter-server-proxy
JUPYTER_TOKEN=secret jupyter-notebook --config=./tests/resources/jupyter_server_config.py &
py.test tests/
```

The only test which passes is `test_utils.py`

**Comment by quasiben** [comment]
I was under the impression that the notebook should also start the servers when navigating to the route.  While I see port 8888 open:

> 1 ❯ lsof -Pn -i4 | grep TCP | grep 8888
python3.7 49777 bzaitlen    7u  IPv4 0x2ae0fc7f824be211      0t0  TCP 127.0.0.1:8888 (LISTEN)

Nothing is returned for `54321` which I thought was the port of the test servers: 
https://github.com/jupyterhub/jupyter-server-proxy/blob/0247bb606bd8161d594e25534a35a8076ba683d1/tests/resources/proxyextension.py#L10

**Comment by manics** [comment]
I've just tried this:
- `pip install .` works- all tests pass
- `pip install -e .` doesn't. I don't know why.

**Comment by quasiben** [comment]
The `-e`, I believe, is comparable to `setup.py develop`.  That is, making things editable from the source directory.  But that worked!  Thanks @manics !!!

**Comment by ian-r-rose** [comment]
I've noticed that notebook server extensions don't enable correctly when using an editable install, and need to be enabled manually:
```
jupyter serverextension enable --sys-prefix jupyter_server_proxy
```
I think this is because the extension metadata files are not copied into the `conf.d` directory that the notebook looks in for server extensions. Might this be the cause of the problem?

**Comment by quasiben** [comment]
@ian-r-rose YES!  That was it.  with `pip install -e .`, {CONDA_PREFIX}/etc has no jupyter directory.  After the extension is enabled etc is populated correctly.  Do you think this is an outlier case?  If not, should I add a note in the README ?

**Comment by ian-r-rose** [comment]
Sure, a note seems reasonable. I think we should probably document this behavior in the `notebook` repository, since it's pretty easy to run into this when developing server extensions.
