### ISSUE TITLE
URLs with pathname containing spaces not supported

### ISSUE THREAD

**Issue by tibdex** [jupyterhub/jupyter-server-proxy#138]
Hi,

Trying to request an URL with a [pathname](https://nodejs.org/api/url.html#url_url_pathname) containing spaces through the proxy leads to HTTP errors such as `400 (Bad request)` or `505 (HTTP Version Not Supported)`.

Here's how you can reproduce:

1. Launch this Node.js server:
   ```javascript
   const http = require("http");
   const port = 3000;

   const requestHandler = (request, response) => {
     response.end(request.url);
   };

   const server = http.createServer(requestHandler);

   server.listen(port, error => {
     if (error) {
       return console.error(error);
     }

     console.log(`listening on ${port}`);
   });
   ```
2. Start a Jupyter server with `jupyter-server-proxy` active
3. Check in your browser that http://localhost:3000/foo%20bar works but http://localhost:8888/proxy/3000/foo%20bar doesn't

Thanks!

**Comment by oeway** [comment]
I encountered the same issue, and tried a quick hack to the code and it seems fixed the issue.

What I did is to edit the file `...python3.6/site-packages/jupyter_server_proxy/handlers.py` in the ProxyHandler:
```python
async def http_get(self, path):
    import urllib.parse
    path = urllib.parse.quote(path)
    return await self.proxy(self.port, path)
```
