### ISSUE TITLE
Issue while starting up Jupiter from Anaconda.

### ISSUE THREAD

**Issue by vinaykumar8** [jupyterhub/jupyter-server-proxy#143]
Hi I'm newbie using Jupiter. please go easy on me. I cant delete a file from the folder and it is showing up the following issues while starting up the Jupiter.

[I 09:11:45.573 NotebookApp] The port 8888 is already in use, trying another port.
[I 09:11:45.573 NotebookApp] The port 8889 is already in use, trying another port.
[I 09:11:45.574 NotebookApp] The port 8890 is already in use, trying another port.
[I 09:11:45.574 NotebookApp] The port 8891 is already in use, trying another port.
[I 09:11:45.684 NotebookApp] JupyterLab extension loaded from C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\jupyterlab
[I 09:11:45.684 NotebookApp] JupyterLab application directory is C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\share\jupyter\lab
[I 09:11:45.687 NotebookApp] Serving notebooks from local directory: C:\Users\c_vinp
[I 09:11:45.687 NotebookApp] The Jupyter Notebook is running at:
[I 09:11:45.687 NotebookApp] http://localhost:8892/?token=5be84edd5b4483db67a52ee0588cc6eec0ef01d73eeaf7af
[I 09:11:45.687 NotebookApp] or http://127.0.0.1:8892/?token=5be84edd5b4483db67a52ee0588cc6eec0ef01d73eeaf7af
[I 09:11:45.687 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:11:45.793 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/c_vinp/AppData/Roaming/jupyter/runtime/nbserver-16408-open.html
Or copy and paste one of these URLs:
http://localhost:8892/?token=5be84edd5b4483db67a52ee0588cc6eec0ef01d73eeaf7af
or http://127.0.0.1:8892/?token=5be84edd5b4483db67a52ee0588cc6eec0ef01d73eeaf7af
[E 09:11:47.472 NotebookApp] Could not open static file ''
[W 09:11:47.989 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (::1) 36.99ms referer=http://localhost:8892/tree?token=5be84edd5b4483db67a52ee0588cc6eec0ef01d73eeaf7af
[W 09:11:53.886 NotebookApp] delete /Test-anaconda/final.csv
[E 09:11:54.958 NotebookApp] Uncaught exception DELETE /api/contents/Test-anaconda/final.csv (::1)
HTTPServerRequest(protocol='http', host='localhost:8892', method='DELETE', uri='/api/contents/Test-anaconda/final.csv', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
result = await result
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
yielded = next(result)
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\contents\handlers.py", line 237, in delete
yield maybe_future(cm.delete(path))
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\contents\manager.py", line 279, in delete
self.delete_file(path)
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\contents\filemanager.py", line 540, in delete_file
send2trash(os_path)
File "C:\Users\c_vinp\AppData\Local\Continuum\anaconda3\lib\site-packages\send2trash\plat_win.py", line 86, in send2trash
raise WindowsError(None, None, path, result)
PermissionError: [WinError 32] None: 'C:\\Users\\c_vinp\\Test-anaconda\\final.csv'
[W 09:11:55.010 NotebookApp] Unhandled error
[E 09:11:55.011 NotebookApp] {
"Host": "localhost:8892",
"Connection": "keep-alive",
"Accept": "application/json, text/javascript, */*; q=0.01",
"Origin": "http://localhost:8892",
"X-Requested-With": "XMLHttpRequest",
"X-Xsrftoken": "2|3fc147c7|5f3f8010be3b366858defe63b0de12df|1564772828",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36",
"Referer": "http://localhost:8892/tree/Test-anaconda",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9",
"Cookie": "_xsrf=2|3fc147c7|5f3f8010be3b366858defe63b0de12df|1564772828; username-localhost-8888=\"2|1:0|10:1564786543|23:username-localhost-8888|44:NTQ2NWE2ZGQzMjIxNDM3OWE1MDc3N2NjZmZmZDkxYTU=|6374bdec9e77ee157fc11c3195270738a5887222146bdf7e6d426315bc879e06\"; username-localhost-8889=\"2|1:0|10:1564786632|23:username-localhost-8889|44:YTdhMzJjNmUwY2JmNDhkN2E1N2FlYTBlYzY0YjE3OTc=|08d4f50fb283a4041ee26b6968868afa7d435f6103976accc0015d567c6f6692\"; username-localhost-8890=\"2|1:0|10:1564970456|23:username-localhost-8890|44:NGE2MGFiN2ExZjE5NGQ5YWE5NWU2NzVlYzljNGUwOWU=|5d5b775d2c34c5bcbc640b6a6294400813edbbfa60d7708ad5b1dcd8052c51e2\"; username-localhost-8891=\"2|1:0|10:1565049790|23:username-localhost-8891|44:OTY2ZTk3Y2Q1MzAzNDA5ZTljMWI5MDJkMWYzOGM0NGM=|5b830d9780b713672c6a5dbef9453763ce4f2adb7964dbea9945948a44daa8b1\"; username-localhost-8972=\"2|1:0|10:1565063853|23:username-localhost-8972|44:MGU4ZDlhZWU2YWNhNGY1MTlmOWU2YWQ1ODhmZjE3OGI=|4603e107f51f779cf56271019e8f50d6fb70f39e44d1c0a231e5ad688338f79b\"; username-localhost-8892=\"2|1:0|10:1565107907|23:username-localhost-8892|44:OWEzYzZlY2Q1YTM2NGQ2YWFmY2VjZGZkYzkyMjc4N2Q=|0ee18ed1b4c2b6d5325da127cdca91987ca8efaaf1a7b2f085050651df3d868c\""
}
[E 09:11:55.011 NotebookApp] 500 DELETE /api/contents/Test-anaconda/final.csv (::1) 1125.99ms referer=http://localhost:8892/tree/Test-anaconda

**Comment by ryanlovett** [comment]
Hello, jupyter-server-proxy does no file management so this is not a bug with this project.

The problem appears to be related to permissions:
> PermissionError: [WinError 32] None: 'C:\Users\c_vinp\Test-anaconda\final.csv'

You might consider getting help with this on the [Jupyter Discourse](https://discourse.jupyter.org).
