### ISSUE TITLE
Proxy to host other than localhost

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/jupyter-server-proxy#152]
It would be really helpful to be able to proxy to another service which is only accessible from the notebook.

My use case here is a Dask cluster running on a Kubernetes cluster that is also running the notebook (z2hj + Pangeo). The notebook can connect to the scheduler at its hostname, but I cannot view the dashboard because the hostname and IP of the dashboard is only routable from within the Kubernetes cluster.

It would be great to be able to do something like:

`/proxy/{hostname}:{port}/`

_This has come up for the first time as [work in `dask-kubernetes`](https://github.com/dask/dask-kubernetes/pull/162) has meant that the scheduler will no longer be running in on the same host as the notebook, and instead be a separate container within the cluster with its own IP and hostname._

**Comment by mrocklin** [comment]
I think that @quasiben did this in https://github.com/dask/distributed/pull/2715

**Comment by jacobtomlinson** [comment]
Ah ok, I did wonder how the worker proxying worked! It looks like that code didn't make its way upstream to here though. Is that something that could be done?

**Comment by mrocklin** [comment]
I think that @yuvipanda was interested in that topic.  I think that he had some concerns about whitelisting known addresses rather than keeping everything open.  Probably there is a way to move most of this upstream while making the list of acceptable addresses pluggable.

**Comment by manics** [comment]
There's a related issue in https://github.com/jupyterhub/jupyter-server-proxy/issues/102

**Comment by ian-r-rose** [comment]
`dask-labextension` uses `jupyter-server-proxy` to proxy to a potentially non-localhost server. That logic is done [here](https://github.com/dask/dask-labextension/blob/d08bd83e9e8ee5aa590a32ddf066118025b2976c/dask_labextension/dashboardhandler.py#L16-L83). It takes some custom python to do it, but is not too bad.

**Comment by jacobtomlinson** [comment]
Thanks @ian-r-rose. I'm hoping to use the vanilla proxy here as I will not be in control of the Jupyter/JupyterHub environment that people will be running dask-kubernetes on.
