### ISSUE TITLE
Unable to install on Jupyterlab 1.0.2

### ISSUE THREAD

**Issue by cristinaserrano** [jupyterhub/jupyter-server-proxy#153]
While trying to install the labextension on jupyterlab 1.0.2 installation fails with following message:

Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/application
>=1.0.1 <2.0.0          >=0.19.1 <0.20.0@jupyterlab/launcher
See the log file for details:  /tmp/jupyterlab-debug-b6xoxgwq.log

It would be really nice if this could be fixed.

Thank you

**Comment by playermanny2** [comment]
Also having this issue...the package.json look like it can support the newer jupyter, but doesn't look like npm has been updated. Can we get a new npm push @betatim @ryanlovett

**Comment by playermanny2** [comment]
@cristinaserrano  can confirm that this is an issue with the npm package not being updated...for the time being created a spin-off package https://www.npmjs.com/package/playermanny2-jupyterlab-server-proxy

Github fork can be found on my profile

**Comment by jhgoebbert** [comment]
It would be great to have a new official release on github and pypi/npmjs of jupyter-server-proxy for JupyterLab 1.x

**Comment by blink1073** [comment]
Fixed in #159
