### ISSUE TITLE
icon_url should be replaced with icon_path in the cookiecutter template

### ISSUE THREAD

**Issue by ka-zo** [jupyterhub/jupyter-server-proxy#162]
Hi @yuvipanda ,

There is an error in the following line:

https://github.com/jupyterhub/jupyter-server-proxy/blob/a937a03fcc9bb21d9cf6b39eefba68915187e0dd/contrib/template/%7B%7Bcookiecutter.project_name%7D%7D/jupyter_%7B%7Bcookiecutter.project_name%7D%7D_proxy/__init__.py#L15

`icon_url` should be `icon_path`. Please fix, otherwise icon shall not be loaded for the GUI launcher, after cookiecutter generates the project from the template.

**Comment by betatim** [comment]
As you've found the problem and diagnosed it, do you want to make a PR to fix this?

**Comment by ka-zo** [comment]
ok. no problem.
