### ISSUE TITLE
Proxy Server configuration ignored/not applied

### ISSUE THREAD

**Issue by dschofield** [jupyterhub/jupyter-server-proxy#167]
I'm running The Littlest Jupyter Hub and attempting to use jupyter-server-proxy to direct traffic to serve notebooks using voila. My traitlet config is as follows:

`#configure hub to manage voila requests
c.ServerProxy.servers = {
  'voila': {
    'command': ['voila', '--port', '{port}', '--server_url', '/', '--base_url', '{base_url}/voila/'],
    'launcher_entry': {'enabled': True, 'title':'schoila'}
  }
}`

However, I see no indication that this works. Any traffic to .../voila results in a 404, I see nothing in the JupyterHub or User logs to indicate that the server proxy exists and is being applied, and no launcher entries are created in either classic or lab views.

Checking <host>://hub/user/<user>/server-proxy/servers-info returns an empty list.

Standalone Voila is working fine and as a server extension.

Is there a simple test (beyond what I've outlined) to see if a proxy server definition has been correctly applied and is being seen and acted on by the server?
Is the traefik proxy that The Littlest Jub uses getting in the way (I don't believe so)?

jupyter-client==5.3.3
jupyter-core==4.5.0
jupyter-server==0.1.1
jupyter-server-proxy==1.2.0
jupyterhub==1.0.0
jupyterlab==1.1.4
jupyterlab-pygments==0.1.0
jupyterlab-s3-browser==0.2.2
jupyterlab-server==1.0.6
jupyterlab-sql==0.3.1

Thanks for continued guidance.

**Comment by manics** [comment]
> `#configure hub to manage voila requests`

jupyter-server-proxy runs in the single-user server, not on the hub side, so it'll have to be configured in `~/.jupyter/jupyter_notebook_config.py` for each user

**Comment by dschofield** [comment]
That's the ticket. Thanks, @manics.
