### ISSUE TITLE
jupyter-theia-proxy 403

### ISSUE THREAD

**Issue by nimengliusha** [jupyterhub/jupyter-server-proxy#168]
i wanna run an instance of theia alongside notebook. Run notebook without jupyterhub can access theia service, but with jupyterhub, it throws error like below:
jupyter-theia-proxy 403 GET [W 2020-01-02 17:03:47.194 SingleUserNotebookApp log:158] 403 GET /hub/notebook/user/DE-a412aeee-2d38-11ea-a577-0255ac100083/theia/services

Anyone knows the reason? Am i missing something?

Thanks for your reply

**Comment by sinamoeini** [comment]
Hi Did you find a solution for this? I am having the same issue
