### ISSUE TITLE
Can I make a 2.0.1 release of the extension?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-server-proxy#176]
I would like to make a patch release of @jupyterlab/server-proxy to allow this extension to be installable both on JupyterLab 1 and 2, instead of only on JupyterLab 1. This is currently restricted due to this part isn't released yet.

https://github.com/jupyterhub/jupyter-server-proxy/blob/80263c5748f1e0da19fe6b54e6b11883d141788f/jupyterlab-server-proxy/package.json#L32-L35

I don't have the permissions to do so though. @Zsailer perhaps you could help out by either making a 2.0.1 release if you agree this make sense or grant me permission to do so.

**Comment by yuvipanda** [comment]
@consideRatio I've made you an owner!

**Comment by yuvipanda** [comment]
Aaah, I only made you owner of the python package, not the npm package. I don't believe I have those rights unfortunately.

**Comment by consideRatio** [comment]
@jasongrout @minrk you are listed at https://www.npmjs.com/package/@jupyterlab/server-proxy as collaborators, could I get help making a release for this package or the power to do so?

**Comment by minrk** [comment]
Looks like you need to be added as a member of the `@jupyterlab` organization on npm to do that and I don't have permission to do so. @jasongrout can you add some jupyterhub team members here to the jupyterhub team I just created on the jupyterlab org?

Or should this package be published under a `@jupyterhub` org on npm instead of `@jupyterlab`?

**Comment by rmg55** [comment]
+1

**Comment by markthebault** [comment]
+1

**Comment by jasongrout** [comment]
>  Looks like you need to be added as a member of the @jupyterlab organization on npm to do that and I don't have permission to do so. @jasongrout can you add some jupyterhub team members here to the jupyterhub team I just created on the jupyterlab org?

@minrk, I just made you an owner of the org. Does that let you do what you need to do?

**Comment by jasongrout** [comment]
@consideRatio - what is your npm username?

**Comment by jasongrout** [comment]
> Or should this package be published under a `@jupyterhub` org on npm instead of `@jupyterlab`?

If you want to take the package into your org, that's great too. Whatever you want.

**Comment by consideRatio** [comment]
@jasongrout thank you I'm consideratio in npm as well!

**Comment by playermanny2** [comment]
Hey @consideRatio -- following up on this,

will 2.0.1 be released on npm soon...getting install error currently w/  jupyterlab 1.0

ValueError: The extension "@jupyterlab/server-proxy" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab              Extension      Package
>=2.1.0 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/application
>=2.1.0 <2.2.0          >=1.0.0 <2.0.0 @jupyterlab/launcher

**Comment by consideRatio** [comment]
Thanks @jasongrout for your help! I've now released the @jupyterlab/server-proxy extension v2.0.1 now which makes us have JupyterLab 2 support! :tada:
