### ISSUE TITLE
New jupyterlab-server-proxy release

### ISSUE THREAD

**Issue by cmd-ntrf** [jupyterhub/jupyter-server-proxy#196]
@ryanlovett released 1.4.0 in b5787024d6ebece3ce23dedf68f97b7f301634f3. A release of the corresponding jupyterlab-server-proxy extension on npm would be nice too.

**Comment by ryanlovett** [comment]
Fixed by https://github.com/jupyterhub/jupyter-server-proxy/issues/175#issuecomment-626977204.
