### ISSUE TITLE
Add links to Jupyter Lab as a launcher(not in a notebook)

### ISSUE THREAD

**Issue by vnijs** [jupyterhub/jupyter-server-proxy#207]
I'm trying to add links to additional documentation for our students that would be accessible from a docker container running Jupyter Lab. I thought about using jupyter-server-proxy to create a "launcher" but got stuck (see post linked below). I know I could add a link to a specific notebook but is not what I'm looking for. Is there a simpler way to do something like this? If not, that would be my feature request. 

https://discourse.jupyter.org/t/create-a-launcher-in-jupyter-lab-to-open-a-specific-url/5077

**Comment by manics** [comment]
This project is for proxying network services, it's not a generic launch manager. In theory you could use this to proxy your entire documentation site but reading your linked post you just want a way to have a JupyterLab launcher open a URL. This is outside the scope of this project. I'll comment on your forum post.
