### ISSUE TITLE
Support JupyterLab 3

### ISSUE THREAD

**Issue by snickell** [jupyterhub/jupyter-server-proxy#219]
With JupyterLab 3 release candidates out, it would be great to have a compatible `jupyter-server-proxy`.

**Comment by snickell** [comment]
For example, RC4 was released last week: https://www.npmjs.com/package/@jupyterlab/application/v/3.0.0-rc.4

**Comment by dipanjank** [comment]
Added https://github.com/jupyterhub/jupyter-server-proxy/pull/229/ if a maintainer can please review.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/how-to-launch-browser-from-jupyterlab/7912/6
