### ISSUE TITLE
Publish version 1.5.2 on pypi

### ISSUE THREAD

**Issue by AndreaGiardini** [jupyterhub/jupyter-server-proxy#228]
### Bug description

Not all versions of jupyter-server-proxy are published on pypi.
Last version published is 1.5.0 : https://pypi.org/project/jupyter-server-proxy/#history
Last version released is 1.5.2 : https://github.com/jupyterhub/jupyter-server-proxy/releases
1.5.1 doesn't seem to exist (?)

#### Expected behaviour

All versions released on github are also present on pypi

#### Actual behaviour

1.5.2 is not available from pypi

**Comment by yuvipanda** [comment]
I just manually published 1.5.2. We should automate that, but for now, this should work.

Thanks for the poke, @AndreaGiardini!
