### ISSUE TITLE
Package the jupyterlab extension with the Python package

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-server-proxy#233]
As @jtpio describes in https://github.com/jupyterhub/jupyter-server-proxy/pull/229#issuecomment-755994606, we can package the jupyterlab extension to install automatically as part of installing the python package!

**Comment by dipanjank** [comment]
I'd like to work on this, if not taken already!

**Comment by consideRatio** [comment]
@dipanjank greatly appreciated! Please mention me for review, I'd like to learn about this procedure :)

**Comment by jtpio** [comment]
Thanks all!

Linking to a couple of resources that might help get this started:

- Using the upgrade script: https://jupyterlab.readthedocs.io/en/stable/extension/extension_migration.html#upgrading-library-versions-using-the-upgrade-script
- Extension tutorial using the Python packaging for distributing the extension: https://jupyterlab.readthedocs.io/en/stable/extension/extension_tutorial.html
- Docs on the prebuilt extensions: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html#prebuilt-extensions

**Comment by janjagusch** [comment]
Hi! I'd also like to give this a try. :)

I would suggest to take inspiration from [jupytext](https://github.com/mwouts/jupytext), where the JL extension has already been packages.

From what I could see I believe you need to
* add a `build:prod` script to the `package.json`
* change the `setup.py` to use `jupyter_packaging`

**Comment by jtpio** [comment]
Nice, thanks @janjagusch!
