### ISSUE TITLE
Custom section for proxy apps in the JupyterLab launcher

### ISSUE THREAD

**Issue by eddienko** [jupyterhub/jupyter-server-proxy#243]
### Proposed change

Currently in the JupyterLab Launcher all proxy apps appear under the Notebook section (see screenshot). This is misleading since these are not notebooks (e.g. desktop server, pgweb, rstudio, ....). Ideally they should be in their own section (e.g. Applications). This probably requires some changes in the JupyterLab code (so that another section can be added).

<img width="976" alt="Screenshot 2021-02-07 at 18 38 33" src="https://user-images.githubusercontent.com/3780274/107156024-bbeda000-6973-11eb-89bf-e25cf491edbf.png">

**Comment by manics** [comment]
There's already an issue for this: https://github.com/jupyterhub/jupyter-server-proxy/issues/145
Please feel free to share your ideas there.
