### ISSUE TITLE
Improve performance of test setup by caching the `./dist` directory

### ISSUE THREAD

**Issue by janjagusch** [jupyterhub/jupyter-server-proxy#246]
Test setup could be improved by caching the `./dist` directory. I would suggest moving that to a separate issue though. :)

_Originally posted by @janjagusch in https://github.com/jupyterhub/jupyter-server-proxy/pull/245#discussion_r574427929_

**Comment by manics** [comment]
We could use https://github.com/actions/upload-artifact and https://github.com/actions/download-artifact, though I think we should keep testing the build on multiple Python versions, and juts use it to skip the `jupyterlab_version` matrix added in https://github.com/jupyterhub/jupyter-server-proxy/pull/245
