### ISSUE TITLE
Jupyterhub in docker required?

### ISSUE THREAD

**Issue by giovanidiniz** [jupyterhub/jupyter-server-proxy#289]
Hi,

i was playing around with my JH instance and I would love to have the option to use my Theia instance from the JLab menu.

I was going over the documentation and couldn’t find any requirements but on a video, @yuvipanda mentions it is necessary to have JH running from docker for this to work. 

Is this still the case?

**Comment by manics** [comment]
Hi! In general we ask that JupyterHub GitHub issues are used for bugs and development discussions, with support being handled on the [community forum](https://discourse.jupyter.org/) where more people hang out, and the rest of the community can benefit from these discussions. Would you mind posting there instead?
