### ISSUE TITLE
Consider using black/pre-commit for nicer code

### ISSUE THREAD

**Issue by maresb** [jupyterhub/jupyter-server-proxy#296]
### Proposed change

Apply the [black](https://github.com/psf/black) code formatter to the existing code.

Add a `.pre-commit-config.yaml` file which runs black before each commit.

### Alternative options

1. Continue without any formatting. This results in uneven code formatting and an increase in merge conflicts over the long-term.

2. Use an alternative formatter. I see that there's an alternative called [blue](https://pypi.org/project/blue/) but I've had no major disagreements with black and it seems to be quite standard.

3. Skip the pre-commit hook. But then there's no enforcement of the formatting, and someone has to regularly perform formatting commits.

### Who would use this feature?

Maintainers and contributors would benefit. It could lead to slightly more effort for new contributors because one must additionally install [pre-commit](https://pre-commit.com), run the `pre-commit install` command, and readd/recommit whenever changes are made.

### (Optional): Suggest a solution

1. See what people think. If people agree...
2. Run black on the existing code. This messes with the "blame" functionality of git, but can be mitigated by [creating a `.git-blame-ignore-revs` file](https://akrabat.com/ignoring-revisions-with-git-blame/). Unfortunately this is [not yet supported by GitHub itself](https://github.com/github/feedback/discussions/5033).
3. Add a `.pre-commit-config.yaml` to run black
4. Assist with open merge requests as well as reasonably possible. For instance, one might be able to use something like [this](https://gist.github.com/ndevenish/a7a9eb93cc19abbfe80f2daab16d3367) to rebase existing PRs.

**Comment by ryanlovett** [comment]
Looks like JupyterHub [is using black](https://github.com/jupyterhub/jupyterhub/blob/f06902aa8f3c0232ae9f1e560c9ae75a7d04a3cf/.pre-commit-config.yaml#L12) as well.

**Comment by consideRatio** [comment]
I'm very much in favor of using black + pre-commit etc, but I know there is trouble to introduce black and such without reducing the amount of open PRs first.

Overall, this repo needs some maintenance love first I think =/

**Comment by consideRatio** [comment]
We should absolutely get black and other autoformatters setup in this repo. I'd go for doing it right now like in many other jupyterhub repos, but there are too many open PRs that I'd like to see resolved before causing merge conflicts etc.
