### ISSUE TITLE
Replace jupyter-notebook by jupyter-lab

### ISSUE THREAD

**Issue by maresb** [jupyterhub/jupyter-server-proxy#297]
### Bug description

[In CONTRIBUTING.md](https://github.com/jupyterhub/jupyter-server-proxy/blob/7d7eae940285b92cff98a66f64d6fa9b8fe5506a/CONTRIBUTING.md?plain=1#L23) it is suggested to use Jupyter Notebook for testing. I haven't touched Notebook for years, and I think it would make more sense to use `jupyter-lab` in place of `jupyter-notebook`.

I also noticed something similar in the CI [where Notebook is referenced](https://github.com/jupyterhub/jupyter-server-proxy/blob/7d7eae940285b92cff98a66f64d6fa9b8fe5506a/.github/workflows/test.yaml#L40). I didn't understand the `matrix.include` construction, but I found ["Including additional values into combinations"](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-additional-values-into-combinations) as a source from which it was apparently copy-pasted and adapted. (As evidence, note the [irrelevant comment about npm](https://github.com/jupyterhub/jupyter-server-proxy/blob/7d7eae940285b92cff98a66f64d6fa9b8fe5506a/.github/workflows/test.yaml#L42).) But the "Including additional values into combinations" section which I linked doesn't seem applicable in this case, rather the ["Including new combinations"](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-including-new-combinations) example seems relevant.

There may be other places where some cleanup is warranted, and I'm not exactly sure how one should clean up the CI. Thus I haven't written a PR.

#### Expected behaviour

The world moves on to JupyterLab, and Notebook is slowly forgotten.

#### Actual behaviour

Notebook seems to still crop up in a few random places.

**Comment by maresb** [comment]
I didn't mean to suggest dropping support completely.

It's probably good to test both in the CI, but it's probably better for contributors to be running the tests using jupyter-lab so that they don't have to install legacy software, right?

**Comment by manics** [comment]
Thanks for clarifying. I think updating the instructions for manual testing makes sense!
