### ISSUE TITLE
Remove yarn.lock: cause of security warnings & maintenance overhead --- or does it serve a purpose?

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-server-proxy#305]
I was about to cut a release, 3.2.0, but then I saw this which made me pause. I don't like to see that just before I make a release, and like many things, it just has to be properly addressed at some point so I figure now.

![image](https://user-images.githubusercontent.com/3837114/143868711-3eb74c6d-d21f-426e-96a5-010bc4265440.png)

I'm thinking that we should not have a lock file: unless it clearly represents the state of something we build and publish. Are we building and publishing something based on the state of this yarn.lock file? We are building and publishing the docker images in the JupyterHub Helm chart based on frozen requirements.txt files, so any dependabot bump and warning serves a purpose, but are we building something from the yarn.lock file like that?

- The yarn.lock file was added by @yuvipanda in https://github.com/jupyterhub/jupyter-server-proxy/pull/68 as part of adding the jupyterlab extension to show launcher entries.
- The yarn.lock file has been renamed and updated several times by dependabot, but only by dependabot - not by any human

I'm thinking that this is a file without purpose at this point, because we don't build based on it and then it just provides misleading security warnings. Is it okay if we delete it?

**Comment by consideRatio** [comment]
I've followed the publish scripts and concluded that even if i corrupt the yarn.lock file to have obvious syntax errors, it runs without issues. That makes me conclude that the yarn.lock file is ignored.

https://github.com/jupyterhub/jupyter-server-proxy/blob/ed557ad7fc91274fe55e8db6680a30b89e4035e6/.github/workflows/publish.yaml#L19-L34

Due to that, I'm finally feeling okay to cut a release of this package right away and not bother about the yarn.lock warnings and errors. Further, that I can open a PR to remove it.

**Comment by bollwyvl** [comment]
Yes, it is common in lab extension.

Keeping around a lock file lets a project actually see what it both ships
(in this case, the prebuilt lab extension) and what it used to ship it
(webpack). It also ensures every contributor and CI machine is running the
same environment, to the extent it can, which will basically _never_ happen
otherwise.

When built, the lab extension also includes a third-party-licenses.json,
which does document exactly what packages are shipped as part of the
webpack bundle.

Losing that piece of reproducibility and provenance is something of a step
back.

**Comment by bollwyvl** [comment]
Right, yarn.lock is not trying to get in your way, and thugs will generally
heal.

Try deleting the yarn lock and re-running jlpm. It will rebuild a new one,
and commit. If that passes CI, then that's probably good to release, as the
tag would contain the record of its build environment.

That will silence your warnings today. But it is a thing that can managed
on an on-going basis to generally maintain sanity.

**Comment by consideRatio** [comment]
@bollwyvl hmmm I didn't understand what you meant. A key question for me to understand if someone has a case for yarn.lock to be version controlled in this repo, and if so, how and when we would opt to bump versions within it.

My discussion was that it seems like yarn.lock isn't used when we publish, and due to that, we shouldn't have it version controlled here.

@bollwyvl do you know if `tljh pack` making use of the yarn.lock file?

**Comment by consideRatio** [comment]
@bollwyvl do you think this repo should or shouldn't version control the yarn.lock file for the jupyterlab extension bundled with the python package maintained in this repo?

**Comment by consideRatio** [comment]
> Right, yarn.lock is not trying to get in your way, and thugs will generally heal. Try deleting the yarn lock and re-running jlpm. It will rebuild a new one, and commit. If that passes CI, then that's probably good to release, as the tag would contain the record of its build environment. That will silence your warnings today. But it is a thing that can managed on an on-going basis to generally maintain sanity.

@bollwyvl sorry! I missed you made two replies and responded without seeing the one quoted above. Okay, is it correct of me to summarize that you think that:
- the yarn.lock file is considered during publishing, influencing software shipped
- we should version control it
- we should keep it updated

Is that correct?

**Comment by consideRatio** [comment]
Debugging into this further I realize that this step considers the yarn.lock file.

https://github.com/jupyterhub/jupyter-server-proxy/blob/ed557ad7fc91274fe55e8db6680a30b89e4035e6/.github/workflows/publish.yaml#L19-L22

Okay I consider the value of having the yarn.lock file is concluded at this point, as it is indeed used to build and ship software somehow as I understand it.

I'm pivoting onwards on how to maintain it, but that is a separate issue. I'll open a new issue.

Thanks for your help @bollwyvl!

**Comment by bollwyvl** [comment]
> - [ ]   the `yarn.lock` file is considered during publishing, influencing software shipped

the `yarn.lock` file is considered when building `node_modules` for the build environment, which includes both the build system and any packages that will be shipped along with it. this might be 0 (but more likely, there will be one or two shims)

> - [x]   we should version control it

yes, it was _designed_ to be deterministically readable under version control, so you can forensically see when your changes to `package.json`, etc. have an impact.

> - [x]    we should keep it updated

It's possible, for example, that re-solving the `yarn.lock` would pull in the new version of `@jupyterlab/builder` that would generate `third-party-licenses.json`
