### ISSUE TITLE
Remove (or add) JupyterLab style

### ISSUE THREAD

**Issue by bollwyvl** [jupyterhub/jupyter-server-proxy#308]
### Proposed change

As of #307, the built `jupyter_server_proxy/labextension/static/third-party-licenses.json` lists `css-loader` and `style-loader`, but `jupyterlab-server-proxy/style/index.css` is empty, so these are not providing much value. So the question is: 

> Do we need any style, and/or would removing it in the future make things more complicated?

### Alternative options

- [ ] delete `index.css` and the reference to it in `index.ts`
- [ ] put something in it

### Who would use this feature?

If removed, this could be a quick yard stick of whether a PR is overcomplicating things, as the best run-time dependencies are _no_ run-time dependencies.

We could then try to _keep_ from shipping any third-party code until it's absolutely necessary. This can be figured out, roughly, by looking at the built `jupyter_server_proxy/labextension/static/third-party-licenses.json`.

### (Optional): Suggest a solution

Some additional style _could_ eventually be nice. If we ever supported log viewing, etc. it would possibly become necessary and better to write it in well-behaved `.css` (where it can be linted, tested, etc) than in fly-by-the-seat-of-your-pants hot style modifications on the frotnend as seems to be popular. I'll _always_ fight against styled-components or whatever that generate classes like `sc-asndicunas sc-easdasd`, and are not stable over time, not matter how nice they are for the developer experience or tiny performance gains.

**Comment by yuvipanda** [comment]
Let's remove it.

**Comment by bollwyvl** [comment]
#314 up!
