### ISSUE TITLE
example of using Jupiter-server-proxy in a Jupiter Hub with streamlit

### ISSUE THREAD

**Issue by joseberlines** [jupyterhub/jupyter-server-proxy#338]
Hi, 

anyone could point out to some instructions/tutorial/video of what is necessary to do to use Jupiter-server-proxy to serve a streamlit app in a Jupiter Hub to other users of the HUB?

thanks.

**Comment by manics** [comment]
Hi :wave: We use GitHub issues for bug reports and developing new features. Do you mind posting this as a support question on https://discourse.jupyter.org/ instead, where more of the community will be able to help? Thanks!
