### ISSUE TITLE
Compatibility with Jupyter Server 2?

### ISSUE THREAD

**Issue by jweill-aws** [jupyterhub/jupyter-server-proxy#347]
Has anyone tested jupyter-server-proxy with Jupyter Server version 2? This version is coming out soon, and users will expect to use the server proxy with it.

@ellisonbg @dlqqq @3coins

**Comment by ellisonbg** [comment]
Thanks for opening this issue @jweill-aws 

I am seeing a problem when using JSP with Jupyter Server 2, but I believe it is a bug in Jupyter Server 2. Details can be found here: https://github.com/jupyter-server/jupyter_server/issues/1012

**Comment by manics** [comment]
This is the current test matrix
https://github.com/jupyterhub/jupyter-server-proxy/blob/a82f70a8b75ce2f8285723c4e4a530a3950c65b7/.github/workflows/test.yaml#L39-L41
I think changing `jupyter_app` to something like `[notebook, jupyterserver1-lab, jupyterserver2-lab]` could be worthwhile?

**Comment by ellisonbg** [comment]
I think it would be helpful to explicitly test JS 2 combinations. I do have at least anecdotal evidence now that JSP work with JS2.

**Comment by consideRatio** [comment]
Seems like there is an issue with the jupyterlab extension tests, but only that.

See https://github.com/jupyterhub/jupyter-server-proxy/actions/runs/3642712327/jobs/6150126621.

**Comment by consideRatio** [comment]
- Closing this in favor of #362 with a focused action point on what to get done
