### ISSUE TITLE
Outdated build system for the jupyterlab extension and failing to update yarn.lock

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-server-proxy#354]
I've struggled to do chore maintenance with the jupyterlab extension. It started by me seing a note about its a good idea to remove yarn.lock to recreate it with new dependencies before relaese. Doing that, things have broken by missing typescript stuff.

I'm not confident on how to do the typical maintenance task associated with the JupyterLab extension.

Is there someone who knows a good reference example to model from with regards to the jupyterlab extension, some relevant documentation to link to, and/or is able to directly help with migrating this extensions possibly outdated stuff in package.json and yarn.lock?

## EDIT: Clarification

What fails is the following, which is fine if yarn.lock remain. The text is from #353 but the current RELEASE.md is describing the same things.

>## Steps to make a release
>
>1. Create a PR updating `jupyterlab-server-proxy/yarl.lock` and continue only
>   when its merged.
>
>   This helps us avoid leaving known vulnerabilities are unfixed. To do this,
>   delete the file and manually perform the the `build dist` step in the
>   `.github/workflows/publish.yaml` workflow's `build` job as summarized below.
>
>   ```shell
>   rm jupyterlab-server-proxy/yarn.lock
>
>   pip install jupyter_packaging wheel jupyterlab~=3.0
>   python setup.py sdist bdist_wheel
>   ```

**Comment by consideRatio** [comment]
- Extension developer guide: https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html
- A cookiecutter example (with typescript as we have): https://github.com/jupyterlab/extension-cookiecutter-ts

**Comment by ryanlovett** [comment]
Thanks for exploring this @consideRatio! I took a setback when the Lab extension material was integrated since I wasn't familiar with that ecosystem. I'd be happy to learn from the experts though.
