### ISSUE TITLE
Modernize packaging infrastructure

### ISSUE THREAD

**Issue by bollwyvl** [jupyterhub/jupyter-server-proxy#370]
### References

- follow-on to #368

### Proposed change

Update the packaging infrastructure to be in line with current common practices e.g. [cookiecutter](https://github.com/jupyterlab/extension-cookiecutter-ts). 

> I'd say "best practices," but i'm still not 100% convinced of the relatively extreme extensibility of `hatch` and the number of things it does _magically_... i actually _prefer_ the relatively bare-bones, but extremely stable, `flit`, and generally use that on my own personal and `$DAY_JOB` projects, with an external tool such as `make` or `doit`.

### Who would use this feature?

- maintainers and contributors _should_ be able to `pip install -e .[atest,docs]` and get a full working dev environment
  - (modulo perhaps `nodejs`, `geckodriver`)

### (Optional): Suggest a solution

- use the `hatch` build backend and plugins to normalize on [`pyproject.toml`](https://github.com/jupyterlab/extension-cookiecutter-ts/blob/3.0/%7B%7Bcookiecutter.python_name%7D%7D/pyproject.toml)
- hoist the `package.json` to the top level of the repo to simplify some of the path stuff
- only ship a single copy of the built assets in the `.whl`

### Alternative options

- do nothing: keep using `setuptools`, etc. with legacy `setup.py` build?
  - will keep working for a while, yet
- keep using `setup.py`, etc. ?
  - add a `pyproject.toml` that declares the build system?
  - move most of the metadata to `setup.cfg`

**Comment by consideRatio** [comment]
I'm 👍 for adoption of hatch and extensive use of pyproject.toml, to the extent setup.py is removed if possible. We have adopted use of hatch in other jupyterhub projects (such as jupyterhub/jupyterhub) to no longer use setup.py for example with good success so i'm fine with adopting it here also.

If possible, i appreciate that we have the code/logic for the labextension separated to reduce the complexity of understanding the project's code files. If its only package.json, thats better than if all files are extracted and a lesser compromise very reasonable to do still.

**Comment by bollwyvl** [comment]
yeah, it would just be `package.json` that would go to the top-level of the repo. but the complexity of getting it into the whl is unavoidable. i'll do a strawman PR.
