### ISSUE TITLE
NPM install failure on `jupyter labextension install @jupyterhub/jupyter-server-proxy`

### ISSUE THREAD

**Issue by prabhakk-mw** [jupyterhub/jupyter-server-proxy#374]
### Bug description
`jupyter labextension install @jupyterhub/jupyter-server-proxy` fails on `jupyter/base-notebook:ubuntu-20.04` with  the following error:
```bash
An error occurred.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-lhvxp028.log
The command '/bin/bash -o pipefail -c jupyter labextension install @jupyterhub/jupyter-server-proxy' returned a non-zero code: 1
```

### How to reproduce

The following `Dockerfile` showcases the issue, and is a simplified version of our production environment:

```Dockerfile
# Filename: Dockerfile.repro-npm-failure
FROM jupyter/base-notebook:ubuntu-20.04 
USER $NB_USER
RUN jupyter labextension install @jupyterhub/jupyter-server-proxy
```

Building this Dockerfile gives us the following results:
```bash
$ docker build --no-cache -f matlab-vnc/Dockerfile.repro-npm-failure -t npmfailure .
Sending build context to Docker daemon  672.3kB
Step 1/3 : FROM jupyter/base-notebook:ubuntu-20.04
 ---> 02fabdbcbde7
Step 2/3 : USER $NB_USER
 ---> Running in 6c0148778619
Removing intermediate container 6c0148778619
 ---> 33944092999d
Step 3/3 : RUN jupyter labextension install @jupyterhub/jupyter-server-proxy
 ---> Running in 1a52068be92e
Building jupyterlab assets (production, minimized)
An error occurred.
RuntimeError: npm dependencies failed to install
See the log file for details:  /tmp/jupyterlab-debug-zs21xnl4.log
The command '/bin/bash -o pipefail -c jupyter labextension install @jupyterhub/jupyter-server-proxy' returned a non-zero code: 1
```

### Your personal set up
Debian 11 
```bash
$ docker version
Client:
 Version:           20.10.5+dfsg1
 API version:       1.41
 Go version:        go1.15.15
 Git commit:        55c4c88
 Built:             Mon May 30 18:34:49 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.5+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.15
  Git commit:       363e9a8
  Built:            Mon May 30 18:34:49 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.13~ds1
  GitCommit:        1.4.13~ds1-1~deb11u3
 runc:
  Version:          1.0.0~rc93+ds1
  GitCommit:        1.0.0~rc93+ds1-5+deb11u2
 docker-init:
  Version:          0.19.0
  GitCommit:        
```

### Workaroud
So far I've been able to work around this issue by applying a `npm config rm https-proxy && npm config rm proxy` before the labextension install as shown in the Dockerfile below:
```Dockerfile
FROM jupyter/base-notebook:ubuntu-20.04 
USER $NB_USER
RUN npm config rm https-proxy && npm config rm proxy && jupyter labextension install @jupyterhub/jupyter-server-proxy
```

Is this right way to fix it? Do you have any other suggestions on what I could try?

Thank you!

**Comment by bollwyvl** [comment]
That `FROM` container is running `jupyterlab 3`. Unless you are somehow _explicitly_ downgrading to `jupyterlab 2`, please use `mamba install` to install the extension. This will ensure: 
- matching server and client components
- the server component dependencies

As `mamba` is not _also_ without warts, see the [upstream Dockerfile](https://github.com/jupyter/docker-stacks/blob/main/base-notebook/Dockerfile#L38) for a size-conscious way of doing the install: basically, you want to install as many packages as you can in a single `RUN` to avoid re-solving the environment every time, which requires downloading an index of available packages.

**Comment by prabhakk-mw** [comment]
Ah! Your comment along with the [README](https://github.com/jupyterhub/jupyter-server-proxy#jupyterlab-extension) clarifies things for me.

Essentially we do not need to install this package explicitly if we are using JupyterLab 3.0! 

Perfect! Thank you @bollwyvl 

Kindly close this bug report if my understanding is correct and you have no other action needed on this!
