### ISSUE TITLE
Release plan for 4.0.0

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/jupyter-server-proxy#388]
Let's plan for the 4.0.0 release!

**Current and proposed breaking changes:**
- #350
- #368
- #387
- #394

**Additional non-blocking nice to get done:**
- #393
- #395 
- Support Windows:
  - Help https://github.com/jupyterhub/simpervisor/pull/26 get merged
  - Help https://github.com/jupyterhub/simpervisor get released
  - Setup tests to run in windows at least once in this repo

**Comment by yuvipanda** [comment]
yes, 100% on keeping jupyter_server 1 support still. I don't have an exact link but somewhere we had to set jupyter_server<2 to preserve compatibility with something else...

**Comment by manics** [comment]
The last release of JupyterLab 2 was in [August 2021](https://pypi.org/project/jupyterlab/2.3.2/). What are the reasons to commit to supporting it for 4.*?

There's discussion in https://github.com/jupyterhub/jupyter-server-proxy/issues/383 about adding new UI components. Without getting into the question of whether we should add new UI components or not, if we do keep JupyterLab 2 it increases the development and testing work required. JupyterLab 4 is also in beta so potentially we'd be supporting three versions soon.

**Comment by consideRatio** [comment]
> The last release of JupyterLab 2 was in [August 2021](https://pypi.org/project/jupyterlab/2.3.2/). What are the reasons to commit to supporting it for 4.*?

With jupyterlab 2 being that old, maybe ~no reason.

👍 For dropping it

**Comment by manics** [comment]
Could we try and get windows support in too? https://github.com/jupyterhub/simpervisor/pull/26

**Comment by consideRatio** [comment]
I added https://github.com/jupyterhub/jupyter-server-proxy/pull/395 to the list of breaking changes as it proposes a change of a API route. I'd love to get that PR part of the release as well no matter what though because it seems like a great feature for this project.

**Comment by consideRatio** [comment]
I figure we shouldn't let #395 block a release, but instead go for faster releases.

@bollwyvl and @manics with #394 in I'll open a changelog PR if you think it makes sense.

**Comment by consideRatio** [comment]
- I also opened #398 that makes sense to merge before a release

**Comment by consideRatio** [comment]
I did `tbump 4.0.0` just a bit too quick, and forgot to refreeze the labextensions yarn.lock file, but cancelled the automation in time to avoid publishing to PyPI/NPM.

I also had to fix the version pattern accepted in `tbump` config.

This is the result, and we have 4.0.0 published.

![image](https://user-images.githubusercontent.com/3837114/233403354-2dd1139e-5e07-48cb-a487-b71b8d905f63.png)

**Comment by consideRatio** [comment]
I downloaded the built wheel and source distribution from https://github.com/jupyterhub/jupyter-server-proxy/actions/runs/4755664077, extracted, and concluded they had the correct checksum, then used `twine` to upload them manually.

I'll fix the checksum issue next.
