### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by jakirkham** [jupyterhub/jupyter-server-proxy#40]
Would be great to have the [minimum Python version requirement]( https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires ). Guessing at least Python 3.5 based on the use of `async`. Is that correct?

**Comment by quasiben** [comment]
I believe this is fixed in the setup.py file:

https://github.com/jupyterhub/jupyter-server-proxy/blob/0247bb606bd8161d594e25534a35a8076ba683d1/setup.py#L14
