### ISSUE TITLE
Operation not supported: '/home/jovyan'

### ISSUE THREAD

**Issue by JJplane** [jupyterhub/jupyter-server-proxy#413]
![image](https://github.com/jupyterhub/jupyter-server-proxy/assets/28783826/63101f7f-eb8f-4256-8ff5-aee2e729f541)

**Comment by manics** [comment]
Hi. This sounds like a configuration problem. Please could you start a topic on the community forum https://discourse.jupyter.org/ and provide full instructions for reproducing your problem? Thanks!
