### ISSUE TITLE
Doesn't work with applications which use absolute URLs

### ISSUE THREAD

**Issue by jacobtomlinson** [jupyterhub/jupyter-server-proxy#43]
I've noticed that a few applications that I've tried to proxy recently use absolute urls.

For example when running on a regular server if you go to `http://localhost:1234/` it will look for a stylesheet at`/style/index.css`. This works fine when running locally but when using nbserverproxy I visit `http://localhost:8888/lab/proxy/1234` which still looks for styles at `/style/index.css` rather than `/lab/proxy/1234/style/index.css`.

These applications often take a `baseurl` config option somewhere which lets you prepend all urls with a base path, such as `/lab/proxy/1234`. This would allow me to fix this functionality. However it appears nbserverproxy rewrites its urls so when I visit `http://localhost:8888/lab/proxy/1234` the path gets rewritten to `/`. This then causes problems because the application is now expecting a base url of `/lab/proxy/1234/`. This results in the HTML page not displaying because flask or whatever doesn't have a route for `/`, but the CSS would display ok if it were ever requested.

**Comment by betatim** [comment]
No real answers, just a short clarification: if you visit `http://localhost:8888/lab/proxy/1234/` (with trailing slash) does that change things at all? It is starting to feel like 'have you tried with trailing slash' should become a FAQ.

**Comment by manics** [comment]
I ran into this last week with a django app (with baseurl=`/proxy/80`, trailing slash in config or accessed URL didn't help). In this particular case it was fronted by Nginx so I could work around by adding a rewrite config: `location / { rewrite ^/(.*)$ /proxy/80/$1 last; }`.

**Comment by jacobtomlinson** [comment]
@betatim No it doesn't make a difference.

@manics Adding nginx or apache would probably work, but I would like to avoid that.

**Comment by betatim** [comment]
We could add an option to (not) rewrite URLs to the proxy? `http://localhost:8888/lab/dont_rewrite_me_proxy/1234/` (maybe a slightly shorter URL ;) )

**Comment by jacobtomlinson** [comment]
That sounds like a pragmatic fix. Perhaps something like `proxy_abs` for absolute urls?

**Comment by psychemedia** [comment]
I've just come across this issue too using Apache Drill.

Includes are of the form:

```
<script src="/static/js/ace-code-editor/mode-snippets.js" type="text/javascript" charset="utf-8"></script>
```

Note also that the UI pages may themselves work at different path levels, eg `http://127.0.0.1:54239/proxy/8047/` or 
 `http://127.0.0.1:54239/proxy/8047/query/`.

**Comment by yuvipanda** [comment]
Hmm, so there are two issues here:

1. Applications that don't take a {base_url} but don't use relative paths & assume they're running at /. I don't think there's anything we can do here
2. Stripping prefix from passed URLs - I think this stripping is needed for some (such as RStudio?) but problematic in others. We should make that configurable.
