### ISSUE TITLE
Process management and the ability to start and stop the launched process

### ISSUE THREAD

**Issue by DeepCowProductions** [jupyterhub/jupyter-server-proxy#475]
Hi and thanks for the project!

Currently, there is no process management of what ever you want to service behind this proxy.
Meaning, if a process crashes or a user want's to restart it, the entire container has to be restarted. 

How much effort be it be to have a list of running services displayed on the left toolbar?
I.e. a new section under here:
![image](https://github.com/jupyterhub/jupyter-server-proxy/assets/26613311/4485384e-a225-4ec2-9861-ae513cd9e546)

**Comment by ryanlovett** [comment]
Hi @DeepCowProductions , this is being worked on in #395.

**Comment by DeepCowProductions** [comment]
Ah, sorry I did not see this, thx :)

**Comment by ryanlovett** [comment]
@DeepCowProductions No worries!
