### ISSUE TITLE
support tcp over websocket

### ISSUE THREAD

**Issue by Cas-pian** [jupyterhub/jupyter-server-proxy#75]
Is there a plan to support TCP over websocket? Thanks

**Comment by ryanlovett** [comment]
I've no plans to implement this directly in the extension, but @yuvipanda might.

You might look into [websockify](novnc) however. I once wrote an alpha-quality extension, [nbnovnc](https://github.com/ryanlovett/nbnovnc), which used it to proxy VNC. I need to update it to work with this extension's 1.0dev.

**Comment by yuvipanda** [comment]
Thanks for opening this issue, @Cas-pian. I agree with @ryanlovett that websockify is the way to go here, and we shouldn't add that functionality into jupyter-server-proxy itself. 

Better websockify link: https://github.com/novnc/websockify

I'm going to close this one now. If you end up using websockify with a TCP server, let us know and we'll happily link to it!

**Comment by Cas-pian** [comment]
Thanks for all your reply. It seems that if I want to tunnelingTCP over jupyter server's connection with I need to develop it base on tornado's websocket handler, right? thanks again.

**Comment by yuvipanda** [comment]
@Cas-pian depending on what exactly you are trying to do, websockify might be enough.

Since this sounds like a wider discussion than just about this repository, can you open a post in discourse.jupyter.org? Thanks.

**Comment by Cas-pian** [comment]
@yuvipanda Thanks! I'll try to take a dig on it and then try to feed back, thanks!

**Comment by yuvipanda** [comment]
Re-opening per https://github.com/jupyterhub/jupyter-server-proxy/pull/447#issuecomment-2085761198
