### ISSUE TITLE
500 server error - timing out on service start 

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/jupyter-server-proxy#81]
Trying to run the [OpenRefine package demo](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html?highlight=time%20out#specifying-config-from-python-packages) as hinted at in the docs, I get a `500 internal server error — could not start openrefine in time`.

Is there an obvious way of setting the time out period?

Also, I can start the OpenRefine server fine from a terminal using a similar command to the one defined in the setup, but if I then try to visit the proxied URL I get the same error; i.e. even though the application is running against the proxied port, it doesn't appear: `jupyter-server-proxy` is presumably try to initiate it itself?

**Comment by yuvipanda** [comment]
@psychemedia can you see what's in the notebook debug logs? Usually this means openrefine is failing immediately on startup...

**Comment by psychemedia** [comment]
I'll try... where do I find the log file?

Ah, right, in the terminal I started `repo2docker` from...

The error was nothing substantive, just the `refine` help dump multiple times, which suggested that the command was ill formed. I was using a specified project directory (with a `-p` switch) as per:

```
def setup_openrefine():
  path = os.path.join(os.environ['HOME'], 'openrefine')
  return {
    'command': ['/home/jovyan/openrefine-2.8/refine', '-p', '3333', '-d', path]
  }
```

but I think it was failing because the directory hadn't been created (I thought OpenRefine created it if it was missing); I fixed that, but now getting:

```
19:43:37.826 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
19:43:37.829 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (3ms)
19:43:37.857 [            refine_server] Initializing context: '/' from '/home/jovyan/openrefine-2.8/webapp' (28ms)
19:43:38.427 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (570ms)
19:43:38.436 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (9ms)
[W 19:43:42.329 NotebookApp] 500 GET /openrefine/ (172.17.0.1): could not start openrefine in time
```

The `FileProjectManager` thing isn't an issue, running`/home/jovyan/openrefine-2.8/refine -p 3333 -d $HOME/openrefine` on the command line goes to completion:

```
jovyan@8299d07038d4:~$ /home/jovyan/openrefine-2.8/refine -p 3333 -d $HOME/openrefine
You have 1998M of free memory.
Your current configuration is set to use 1400M of memory.
OpenRefine can run better when given more memory. Read our FAQ on how to allocate more memory here:
https://github.com/OpenRefine/OpenRefine/wiki/FAQ:-Allocate-More-Memory
Starting OpenRefine at 'http://127.0.0.1:3333/'

19:45:04.896 [            refine_server] Starting Server bound to '127.0.0.1:3333' (0ms)
19:45:04.899 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (3ms)
19:45:04.924 [            refine_server] Initializing context: '/' from '/home/jovyan/openrefine-2.8/webapp' (25ms)
19:45:05.458 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (534ms)
19:45:05.467 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (9ms)
19:45:09.863 [                   refine] Sorry, some error prevented us from launching the browser for you.

 Point your browser to http://127.0.0.1:3333/ to start using Refine. (4396ms)

```

FWIW, I noticed on the littlest Jupyterhub demo on Digital Ocean, I was getting a time out running that too... Do you run everything on superfast machines?! I generally run low specs...

**Comment by psychemedia** [comment]
So it doesn't time out all the time.. it's just come up now:

```
Starting OpenRefine at 'http://127.0.0.1:54491/'

20:10:16.493 [            refine_server] Starting Server bound to '127.0.0.1:54491' (0ms)
20:10:16.496 [            refine_server] refine.memory size: 1400M JVM Max heap: 1407188992 (3ms)
20:10:16.520 [            refine_server] Initializing context: '/' from '/home/jovyan/openrefine-2.8/webapp' (24ms)
20:10:17.023 [                   refine] Starting OpenRefine 2.8 [TRUNK]... (503ms)
20:10:17.034 [       FileProjectManager] Failed to load workspace from any attempted alternatives. (11ms)
[W 20:10:17.272 NotebookApp] 413 GET /openrefine/ (172.17.0.1) 1446.99ms referer=http://127.0.0.1:56886/tree
20:10:21.618 [                   refine] Sorry, some error prevented us from launching the browser for you.

 Point your browser to http://127.0.0.1:54491/ to start using Refine. (4584ms)

```

on a setting of:

```
def setup_openrefine():
  path = os.path.join(os.environ['HOME'], 'openrefine')
  return {
    'command': ['/home/jovyan/openrefine-2.8/refine', '-p', '{port}','-d',path]
  }
```
but I get a blank page and a browser default `HTTP ERROR 413` notification.

**Comment by psychemedia** [comment]
Hmm.. so: if I use `'command': ['/home/jovyan/openrefine-2.8/refine', '-p', '{port}','-d',path]` it works, but if I use `command': ['/home/jovyan/openrefine-2.8/refine', '-p', '3333,'-d',path` it doesn't.

My use case is driving OpenRefine from a py client, so I need to know the port number. 

I can do this when running locally from the notebook server log, but Is there any way I can pick up what port is being used if I don't have access to the notebook log, such as when running in MyBinder?

In this case, what I'm looking for is setting s/thing like:

```
os.environ['OPENREFINE_HOST']='127.0.0.1'
os.environ['OPENREFINE_PORT']='{port}'
```

**Comment by yuvipanda** [comment]
@psychemedia ah, right. we don't let you specify the port from command - it is automatically generated for you by server-proxy. From your python client, can you try hitting the notebook-url/openrefine instead as URL rather than directly to openrefine? Although that might also have auth issues from Python.

We could support setting port explicitly in the spec easily though.

**Comment by psychemedia** [comment]
Out of the can, the client listens for traffic on localhost network inside the container. If the proxy could expose what service is on what internal port, that would be really handy.
