### ISSUE TITLE
Allow user to specify port

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/jupyter-server-proxy#87]
From exploring running various services using `jupyter-server-proxy`:

- some services run on generally recognised ports, albeit allowing users to start pass a port number as an argument to the command that starts the service (eg OpenRefine on port 3333); downstream applications may assume this port number;
- some services appear to run on a default port that cannot be reassigned as part as the start-up command (eg pgAdmin4?)
- the parameter used to set the port may be arbitrarily named and as such hard to identify unambiguously in a command string;

It would be useful to be able to specify a default port number, e.g as:

```
c.ServerProxy.servers = {
    'aService': {
        'command': ['serviceCommand', '--p', '{port}'],
        'timeout': 120,
        'port' : MYPORT, #an optional argument specifying the required port number
        'launcher_entry': {
            'enabled': True,
            'title': 'myService',
        },
    },
}
```

See also: https://github.com/jupyterhub/jupyter-server-proxy/issues/81

**Comment by ChandaniM123** [comment]
I am really looking forward for this change as I would like to pass the port the server process should run on.  Is this change coming anytime soon?

**Comment by manics** [comment]
@psychemedia @ChandaniM123 Would you like to test https://github.com/jupyterhub/jupyter-server-proxy/pull/96? You can install it with `pip install https://github.com/manics/jupyter-server-proxy/archive/config-port.zip`

**Comment by psychemedia** [comment]
@manics Seems to work fine on MyBinder.

(For some reason, `nbserverproxy` has stopped working under `repo2docker` locally on my Mac when it comes to trying to view UIs created on proxied ports.)
