### ISSUE TITLE
Proxying relative URLs in redirects

### ISSUE THREAD

**Issue by ian-r-rose** [jupyterhub/jupyter-server-proxy#88]
In gitter I was chatting with @yuvipanda about the possibility of proxying one version of JupyterLab (specifically using `--dev-mode`) underneath the main one running in binder. https://gitter.im/jupyterhub/binder?at=5c42411983189945240fa7af

In trying this I ran into an issue with redirects. The proxied notebook server returns several redirects towards the default page, but when these redirects (e.g., to `/lab`), are received by the outer notebook server, they are then used to proxy to a page there rather than a page on the proxied server. This is not the effect I was looking for, and it seems to make pages in the proxied server entirely inaccessible if there is a redirect in the way.

This can be tested locally in [this branch](https://github.com/ian-r-rose/jupyterlab/tree/binder-pr) by running `jupyter notebook --config=binder/config.py`. Any thoughts on how to move forward?

I don't know a ton about the right language around proxies, so apologies if this is using the wrong language or is easily fixable :)

**Comment by manics** [comment]
Can you give https://github.com/jupyterhub/jupyter-server-proxy/pull/85 a go? It should pass the external URL directly to the backend.

**Comment by yuvipanda** [comment]
@ian-r-rose I think what you need is base_url, rather than absolute URLs. I made a PR https://github.com/ian-r-rose/jupyterlab/pull/1 that sets base_url, check it out and let me know if that works.

**Comment by ian-r-rose** [comment]
@manics Thanks for the tip! I'll give that a shot.

**Comment by yuvipanda** [comment]
@manics is absolutely right and this is fixed by passing absolute URL back. I'll play around with merging #85 today.

**Comment by yuvipanda** [comment]
And apologies for going on a tangent instead of investigating your PR, @manics!

**Comment by psychemedia** [comment]
I'm not sure I understand the `absolute_url` setting. eg trying it set to `True` when [trying to proxy `datasette`](https://github.com/psychemedia/jupyterserverproxy-datasette-demo) gets me into a redirect loop?

**Comment by manics** [comment]
- `/proxy/12345/sub/path` will rewrite the proxied URL so the application see `/sub/path`, but with HTTP headers to indicate it's running under `/proxy/12345`
- `/proxy/absolute/12345/sub/path` passes the full URL directly so the application sees `/proxy/absolute/12345/sub/path` and no special headers are set

Also see my reply on https://discourse.jupyter.org/t/pgadmin-in-mybinder/365/6?u=manics

**Comment by ian-r-rose** [comment]
@yuvipanda This was fixed by #85, right?
