### ISSUE TITLE
[DOC] Add install_requires

### ISSUE THREAD

**Issue by xmnlab** [jupyterhub/jupyter-server-proxy#90]
hey everyone! I've started to play with this library. it seems very interesting. congrats.

Maybe on https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html `2. Make an appropriate setup.py` would be good to add `install_requires=['jupyter-server-proxy']`

if it makes sense I can open a PR.

**Comment by ryanlovett** [comment]
Yes, it'd be great if you could open a PR, thanks!

**Comment by yuvipanda** [comment]
@xmnlab glad you find it useful! Yes, a PR would be great :)

**Comment by xmnlab** [comment]
awesome. I will work on that :) thanks
