### ISSUE TITLE
Typo base_url on arbitrary-ports

### ISSUE THREAD

**Issue by xmnlab** [jupyterhub/jupyter-server-proxy#98]
it seems there is a typo at:

https://github.com/jupyterhub/jupyter-server-proxy/commit/76b66e3e8fc9d2a1a91a52e8e17f50bb7923be5a#diff-dbc2a7f130ab114ef12a8c43c030908bR80

it uses `base_url` but the variable that was created is `baseUrl`.

It is a small issue but I can create a PR to fix that :)

**Comment by ryanlovett** [comment]
Fixed by #135.
